### ISSUE TITLE
Failed to load the gitlab-integration package

### ISSUE THREAD

**Issue by Batigolle** [blakawk/gitlab-integration#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [gitlab-integration](https://github.com/blakawk/gitlab-integration) package 0.4.7

### Stack Trace

Failed to load the gitlab-integration package

```
At Cannot find module 'protocols'

Error: Cannot find module 'protocols'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.25.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.25.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/gitlab-integration/node_modules/parse-url/lib/index.js:4:17)
    at /packages/gitlab-integration/node_modules/parse-url/lib/index.js:104:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/gitlab-integration/node_modules/git-up/lib/index.js:5:16)
    at /packages/gitlab-integration/node_modules/git-up/lib/index.js:53:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/gitlab-integration/node_modules/git-url-parse/lib/index.js:3:13)
    at /packages/gitlab-integration/node_modules/git-url-parse/lib/index.js:153:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
docblockr 0.13.7 
file-icons 2.1.18 
git-clone 0.2.0 
gitlab-integration 0.4.7 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
```

**Comment by blakawk** [comment]
@Batigolle I tried to reproduce your issue but wasn't able to do so. `gitlab-integration` packages depends on `git-url-parse` module that should correctly pull the `protocols` module. Can you try to remove `gitlab-integration` from Atom and install it through CLI using `apm install gitlab-integration` ?

**Comment by Batigolle** [comment]
Hi @blakawk 
I followed your instructions, uninstalled from Atom and reinstalled from the CLI command line
I have not received any error message, successful installation
Thanks
